apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ljparfan22/sideshop-auth
          # readinessProbe:
          #   tcpSocket:
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          ports:
            - containerPort: 3000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: db-password
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: db-type
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: db-name
            - name: DB_SYNCHRONIZE
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: db-synchronize
            - name: DB_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: db-logging
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: aws-s3-bucket-name
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: aws-region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: inventory-secret
                  key: aws-secret-access-key
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: server-port
            - name: SERVICE_NAME
              value: auth-service
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: access-token-secret
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: refresh-token-secret
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: twilio-account-sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: twilio-auth-token
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: twilio-phone-number
            - name: KAFKA_URL
              value: kafka-service:9092
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
